/**
 * On-device gazetteer used to auto-file items by place. No network lookups.
 *
 * - `name` becomes the folder name ("Bangalore").
 * - `aliases` are other names for the same place ("bengaluru", "blr", "namma bengaluru").
 * - `areas` are neighbourhoods/landmarks that imply the place ("koramangala").
 * - `level`: 3 = city/destination, 2 = state/region, 1 = country. When two
 *   places score the same, the more specific one wins.
 */
export interface PlaceDef {
  name: string;
  emoji: string;
  level: 1 | 2 | 3;
  aliases?: string[];
  areas?: string[];
}

export const PLACES: PlaceDef[] = [
  // ── India: metros ────────────────────────────────────────────────────────
  {
    name: 'Bangalore',
    emoji: '🌳',
    level: 3,
    aliases: ['bengaluru', 'bangaluru', 'blr', 'namma bengaluru', 'namma bangalore', 'bengalore', 'banglore'],
    areas: [
      'koramangala', 'indiranagar', 'indira nagar', 'hsr layout', 'whitefield', 'jayanagar',
      'jp nagar', 'btm layout', 'malleshwaram', 'malleswaram', 'basavanagudi', 'electronic city',
      'marathahalli', 'hebbal', 'yelahanka', 'mg road bangalore', 'brigade road', 'church street bangalore',
      'bannerghatta', 'sarjapur', 'bellandur', 'rajajinagar', 'banashankari', 'ulsoor', 'halasuru',
      'frazer town', 'cubbon park', 'lalbagh', 'lal bagh', 'vv puram', 'jakkur', 'kr puram',
      'domlur', 'cunningham road', 'sadashivanagar', 'rr nagar', 'kengeri', 'hennur',
      'kammanahalli', 'bmtc', 'namma metro', 'kempegowda', 'manyata tech park', 'iisc bangalore',
    ],
  },
  {
    name: 'Mumbai',
    emoji: '🌊',
    level: 3,
    aliases: ['bombay', 'mumbai city', 'aamchi mumbai'],
    areas: [
      'bandra', 'andheri', 'juhu', 'colaba', 'powai', 'lower parel', 'worli', 'dadar',
      'marine drive', 'gateway of india', 'versova', 'malad', 'borivali', 'chembur',
      'kurla', 'goregaon', 'khar', 'santacruz', 'fort mumbai', 'kala ghoda', 'bkc',
      'bandra kurla complex', 'mumbai local',
    ],
  },
  {
    name: 'Delhi',
    emoji: '🏛️',
    level: 3,
    aliases: ['new delhi', 'dilli', 'delhi ncr', 'ncr'],
    areas: [
      'connaught place', 'hauz khas', 'chandni chowk', 'karol bagh', 'lajpat nagar',
      'khan market', 'india gate', 'qutub minar', 'red fort', 'sarojini nagar',
      'rajouri garden', 'greater kailash', 'vasant kunj', 'majnu ka tilla', 'janpath',
      'paharganj', 'mehrauli', 'delhi metro',
    ],
  },
  {
    name: 'Chennai',
    emoji: '🛕',
    level: 3,
    aliases: ['madras'],
    areas: [
      't nagar', 'adyar', 'besant nagar', 'mylapore', 'velachery', 'anna nagar',
      'nungambakkam', 'marina beach', 'egmore', 'guindy', 'tambaram', 'omr chennai',
      'ecr chennai', 'elliots beach',
    ],
  },
  {
    name: 'Hyderabad',
    emoji: '🕌',
    level: 3,
    aliases: ['hyd', 'secunderabad', 'cyberabad'],
    areas: [
      'banjara hills', 'jubilee hills', 'gachibowli', 'hitech city', 'hi tech city', 'madhapur',
      'charminar', 'kondapur', 'kukatpally', 'begumpet', 'ameerpet', 'golconda', 'hussain sagar',
    ],
  },
  {
    name: 'Kolkata',
    emoji: '🚋',
    level: 3,
    aliases: ['calcutta'],
    areas: ['howrah', 'new town kolkata', 'gariahat', 'ballygunge', 'victoria memorial'],
  },
  {
    name: 'Pune',
    emoji: '🏙️',
    level: 3,
    aliases: ['poona'],
    areas: ['koregaon park', 'viman nagar', 'baner', 'hinjewadi', 'kothrud', 'kalyani nagar', 'aundh', 'shivaji nagar pune', 'fc road'],
  },
  { name: 'Ahmedabad', emoji: '🪁', level: 3, aliases: ['amdavad'], areas: ['sg highway', 'sabarmati'] },
  { name: 'Gurgaon', emoji: '🏙️', level: 3, aliases: ['gurugram'], areas: ['cyber hub', 'sohna road'] },
  { name: 'Noida', emoji: '🏙️', level: 3, aliases: ['greater noida'] },
  { name: 'Navi Mumbai', emoji: '🌉', level: 3, aliases: ['vashi', 'kharghar'] },
  { name: 'Thane', emoji: '🏙️', level: 3 },

  // ── India: cities & destinations ─────────────────────────────────────────
  { name: 'Mysore', emoji: '🏰', level: 3, aliases: ['mysuru'], areas: ['mysore palace', 'chamundi hills'] },
  { name: 'Mangalore', emoji: '🐟', level: 3, aliases: ['mangaluru', 'kudla'] },
  { name: 'Udupi', emoji: '🛕', level: 3, areas: ['malpe'] },
  { name: 'Hubli', emoji: '🏙️', level: 3, aliases: ['hubballi', 'hubli dharwad', 'dharwad'] },
  { name: 'Belgaum', emoji: '🏙️', level: 3, aliases: ['belagavi'] },
  { name: 'Coorg', emoji: '☕', level: 3, aliases: ['kodagu', 'madikeri'] },
  { name: 'Chikmagalur', emoji: '☕', level: 3, aliases: ['chikkamagaluru', 'mullayanagiri'] },
  { name: 'Hampi', emoji: '🪨', level: 3 },
  { name: 'Gokarna', emoji: '🏖️', level: 3 },
  { name: 'Nandi Hills', emoji: '🌄', level: 3 },
  { name: 'Ooty', emoji: '🚂', level: 3, aliases: ['udhagamandalam', 'ooty hills'] },
  { name: 'Kodaikanal', emoji: '🌲', level: 3 },
  { name: 'Coimbatore', emoji: '🏙️', level: 3, aliases: ['kovai'] },
  { name: 'Madurai', emoji: '🛕', level: 3 },
  { name: 'Pondicherry', emoji: '🏖️', level: 3, aliases: ['puducherry', 'pondy'], areas: ['auroville'] },
  { name: 'Kochi', emoji: '⛵', level: 3, aliases: ['cochin', 'ernakulam'], areas: ['fort kochi'] },
  { name: 'Munnar', emoji: '🍃', level: 3 },
  { name: 'Wayanad', emoji: '🌿', level: 3 },
  { name: 'Alleppey', emoji: '🛶', level: 3, aliases: ['alappuzha'] },
  { name: 'Varkala', emoji: '🏖️', level: 3 },
  { name: 'Thiruvananthapuram', emoji: '🌴', level: 3, aliases: ['trivandrum'] },
  { name: 'Visakhapatnam', emoji: '⚓', level: 3, aliases: ['vizag'], areas: ['araku valley', 'araku'] },
  { name: 'Vijayawada', emoji: '🏙️', level: 3 },
  { name: 'Tirupati', emoji: '🛕', level: 3, aliases: ['tirumala'] },
  { name: 'Goa', emoji: '🏖️', level: 3, aliases: ['panaji', 'panjim'], areas: ['baga', 'anjuna', 'calangute', 'palolem', 'vagator', 'candolim', 'arambol', 'morjim'] },
  { name: 'Lonavala', emoji: '⛰️', level: 3, aliases: ['khandala'] },
  { name: 'Mahabaleshwar', emoji: '🍓', level: 3 },
  { name: 'Nashik', emoji: '🍇', level: 3, aliases: ['nasik'] },
  { name: 'Nagpur', emoji: '🍊', level: 3 },
  { name: 'Aurangabad', emoji: '🏛️', level: 3, aliases: ['ajanta', 'ellora'] },
  { name: 'Jaipur', emoji: '🏰', level: 3, aliases: ['pink city'], areas: ['amer fort', 'amber fort', 'hawa mahal'] },
  { name: 'Udaipur', emoji: '🏞️', level: 3, aliases: ['city of lakes'] },
  { name: 'Jodhpur', emoji: '🏰', level: 3, aliases: ['blue city'] },
  { name: 'Jaisalmer', emoji: '🐪', level: 3 },
  { name: 'Pushkar', emoji: '🐪', level: 3 },
  { name: 'Agra', emoji: '🕌', level: 3, areas: ['taj mahal'] },
  { name: 'Varanasi', emoji: '🪔', level: 3, aliases: ['banaras', 'benares', 'kashi'] },
  { name: 'Lucknow', emoji: '🕌', level: 3 },
  { name: 'Rishikesh', emoji: '🧘', level: 3 },
  { name: 'Haridwar', emoji: '🪔', level: 3 },
  { name: 'Dehradun', emoji: '🌲', level: 3 },
  { name: 'Mussoorie', emoji: '⛰️', level: 3 },
  { name: 'Nainital', emoji: '🏞️', level: 3 },
  { name: 'Manali', emoji: '🏔️', level: 3, areas: ['solang', 'rohtang'] },
  { name: 'Shimla', emoji: '🏔️', level: 3 },
  { name: 'Kasol', emoji: '🏕️', level: 3, aliases: ['parvati valley'] },
  { name: 'Dharamshala', emoji: '🏔️', level: 3, aliases: ['mcleodganj', 'mcleod ganj'] },
  { name: 'Spiti', emoji: '🏔️', level: 3, aliases: ['spiti valley'] },
  { name: 'Leh', emoji: '⛰️', level: 3, aliases: ['ladakh', 'leh ladakh'], areas: ['pangong', 'nubra'] },
  { name: 'Srinagar', emoji: '🛶', level: 3, areas: ['dal lake', 'gulmarg', 'pahalgam', 'sonamarg'] },
  { name: 'Amritsar', emoji: '🛕', level: 3, areas: ['golden temple'] },
  { name: 'Chandigarh', emoji: '🌹', level: 3 },
  { name: 'Darjeeling', emoji: '🍵', level: 3 },
  { name: 'Gangtok', emoji: '🏔️', level: 3, aliases: ['sikkim'] },
  { name: 'Shillong', emoji: '🌧️', level: 3, aliases: ['cherrapunji', 'sohra'] },
  { name: 'Guwahati', emoji: '🏞️', level: 3 },
  { name: 'Bhubaneswar', emoji: '🛕', level: 3, areas: ['konark'] },
  { name: 'Indore', emoji: '🍲', level: 3, areas: ['sarafa bazaar', 'chappan dukan'] },
  { name: 'Bhopal', emoji: '🏞️', level: 3 },
  { name: 'Surat', emoji: '💎', level: 3 },
  { name: 'Vadodara', emoji: '🏛️', level: 3, aliases: ['baroda'] },
  { name: 'Patna', emoji: '🏙️', level: 3 },
  { name: 'Ranchi', emoji: '🌳', level: 3 },
  { name: 'Raipur', emoji: '🏙️', level: 3 },
  { name: 'Andaman', emoji: '🏝️', level: 3, aliases: ['andaman and nicobar', 'port blair', 'havelock island', 'havelock', 'swaraj dweep', 'neil island'] },
  { name: 'Lakshadweep', emoji: '🏝️', level: 3 },

  // ── India: states & regions ──────────────────────────────────────────────
  { name: 'Karnataka', emoji: '🗺️', level: 2 },
  { name: 'Kerala', emoji: '🌴', level: 2, aliases: ["god's own country", 'gods own country'] },
  { name: 'Tamil Nadu', emoji: '🗺️', level: 2 },
  { name: 'Maharashtra', emoji: '🗺️', level: 2 },
  { name: 'Rajasthan', emoji: '🐪', level: 2 },
  { name: 'Himachal', emoji: '🏔️', level: 2, aliases: ['himachal pradesh'] },
  { name: 'Uttarakhand', emoji: '🏔️', level: 2 },
  { name: 'Kashmir', emoji: '🏔️', level: 2, aliases: ['jammu and kashmir'] },
  { name: 'Northeast India', emoji: '🌿', level: 2, aliases: ['north east india', 'meghalaya', 'arunachal', 'nagaland', 'assam'] },
  { name: 'Telangana', emoji: '🗺️', level: 2 },
  { name: 'Andhra Pradesh', emoji: '🗺️', level: 2 },
  { name: 'Gujarat', emoji: '🗺️', level: 2, areas: ['rann of kutch', 'kutch'] },
  { name: 'West Bengal', emoji: '🗺️', level: 2 },
  { name: 'Punjab', emoji: '🌾', level: 2 },
  { name: 'Madhya Pradesh', emoji: '🐅', level: 2 },
  { name: 'Uttar Pradesh', emoji: '🗺️', level: 2 },
  { name: 'Odisha', emoji: '🗺️', level: 2, aliases: ['orissa'] },
  { name: 'India', emoji: '🇮🇳', level: 1, aliases: ['bharat', 'incredible india'] },

  // ── Asia ─────────────────────────────────────────────────────────────────
  { name: 'Dubai', emoji: '🏙️', level: 3, areas: ['burj khalifa', 'dubai mall', 'jumeirah', 'deira'] },
  { name: 'Abu Dhabi', emoji: '🕌', level: 3 },
  { name: 'Doha', emoji: '🏙️', level: 3 },
  { name: 'Singapore', emoji: '🦁', level: 3, areas: ['marina bay', 'sentosa', 'orchard road'] },
  { name: 'Kuala Lumpur', emoji: '🏙️', level: 3 },
  { name: 'Bangkok', emoji: '🛺', level: 3 },
  { name: 'Phuket', emoji: '🏝️', level: 3 },
  { name: 'Pattaya', emoji: '🏖️', level: 3 },
  { name: 'Krabi', emoji: '🏝️', level: 3 },
  { name: 'Chiang Mai', emoji: '🐘', level: 3 },
  { name: 'Bali', emoji: '🌺', level: 3, areas: ['ubud', 'seminyak', 'canggu', 'uluwatu', 'nusa penida'] },
  { name: 'Hanoi', emoji: '🍜', level: 3 },
  { name: 'Ho Chi Minh City', emoji: '🛵', level: 3, aliases: ['saigon'] },
  { name: 'Da Nang', emoji: '🏖️', level: 3, aliases: ['hoi an'] },
  { name: 'Tokyo', emoji: '🗼', level: 3, areas: ['shibuya', 'shinjuku', 'akihabara', 'harajuku', 'asakusa'] },
  { name: 'Kyoto', emoji: '⛩️', level: 3 },
  { name: 'Osaka', emoji: '🏯', level: 3 },
  { name: 'Seoul', emoji: '🏙️', level: 3, areas: ['gangnam', 'myeongdong', 'hongdae'] },
  { name: 'Hong Kong', emoji: '🌃', level: 3 },
  { name: 'Shanghai', emoji: '🌃', level: 3 },
  { name: 'Beijing', emoji: '🏯', level: 3 },
  { name: 'Taipei', emoji: '🏙️', level: 3 },
  { name: 'Kathmandu', emoji: '🏔️', level: 3, areas: ['thamel', 'pokhara'] },
  { name: 'Colombo', emoji: '🌴', level: 3 },
  { name: 'Maldives', emoji: '🏝️', level: 3, aliases: ['male maldives'] },
  { name: 'Bhutan', emoji: '🏔️', level: 1, aliases: ['thimphu', 'paro'] },
  { name: 'Nepal', emoji: '🏔️', level: 1 },
  { name: 'Sri Lanka', emoji: '🌴', level: 1, aliases: ['srilanka'], areas: ['kandy', 'galle', 'sigiriya'] },
  { name: 'Thailand', emoji: '🐘', level: 1 },
  { name: 'Vietnam', emoji: '🍜', level: 1, aliases: ['viet nam'] },
  { name: 'Indonesia', emoji: '🌋', level: 1 },
  { name: 'Malaysia', emoji: '🌴', level: 1, areas: ['langkawi', 'penang'] },
  { name: 'Japan', emoji: '🗾', level: 1 },
  { name: 'South Korea', emoji: '🇰🇷', level: 1, aliases: ['korea'] },
  { name: 'China', emoji: '🇨🇳', level: 1 },
  { name: 'UAE', emoji: '🇦🇪', level: 1, aliases: ['united arab emirates'] },
  { name: 'Turkey', emoji: '🇹🇷', level: 1, aliases: ['turkiye'], areas: ['cappadocia', 'antalya'] },
  { name: 'Istanbul', emoji: '🕌', level: 3 },

  // ── Europe ───────────────────────────────────────────────────────────────
  { name: 'London', emoji: '🎡', level: 3, areas: ['soho london', 'camden', 'shoreditch', 'notting hill', 'westminster'] },
  { name: 'Paris', emoji: '🗼', level: 3, areas: ['eiffel tower', 'montmartre', 'le marais'] },
  { name: 'Amsterdam', emoji: '🚲', level: 3 },
  { name: 'Berlin', emoji: '🐻', level: 3 },
  { name: 'Munich', emoji: '🍺', level: 3, aliases: ['munchen'] },
  { name: 'Rome', emoji: '🏛️', level: 3, aliases: ['roma'] },
  { name: 'Venice', emoji: '🛶', level: 3, aliases: ['venezia'] },
  { name: 'Florence', emoji: '🎨', level: 3, aliases: ['firenze'] },
  { name: 'Milan', emoji: '👗', level: 3, aliases: ['milano'] },
  { name: 'Barcelona', emoji: '🏖️', level: 3 },
  { name: 'Madrid', emoji: '🏙️', level: 3 },
  { name: 'Lisbon', emoji: '🚃', level: 3, aliases: ['lisboa'] },
  { name: 'Prague', emoji: '🏰', level: 3 },
  { name: 'Vienna', emoji: '🎻', level: 3, aliases: ['wien'] },
  { name: 'Zurich', emoji: '🏔️', level: 3 },
  { name: 'Interlaken', emoji: '🏔️', level: 3 },
  { name: 'Santorini', emoji: '🏝️', level: 3 },
  { name: 'Athens', emoji: '🏛️', level: 3 },
  { name: 'Edinburgh', emoji: '🏰', level: 3 },
  { name: 'Dublin', emoji: '☘️', level: 3 },
  { name: 'Reykjavik', emoji: '🧊', level: 3 },
  { name: 'Switzerland', emoji: '🏔️', level: 1, aliases: ['swiss alps'] },
  { name: 'Italy', emoji: '🍝', level: 1 },
  { name: 'France', emoji: '🥐', level: 1 },
  { name: 'Spain', emoji: '💃', level: 1 },
  { name: 'Germany', emoji: '🇩🇪', level: 1 },
  { name: 'Greece', emoji: '🏛️', level: 1 },
  { name: 'Iceland', emoji: '🧊', level: 1 },
  { name: 'UK', emoji: '🇬🇧', level: 1, aliases: ['united kingdom', 'england', 'scotland'] },
  { name: 'Europe', emoji: '🇪🇺', level: 1 },

  // ── Americas, Oceania, Africa ────────────────────────────────────────────
  { name: 'New York', emoji: '🗽', level: 3, aliases: ['nyc', 'new york city', 'manhattan', 'brooklyn'], areas: ['times square', 'central park'] },
  { name: 'San Francisco', emoji: '🌉', level: 3, aliases: ['bay area'] },
  { name: 'Los Angeles', emoji: '🌴', level: 3 },
  { name: 'Las Vegas', emoji: '🎰', level: 3 },
  { name: 'Seattle', emoji: '☕', level: 3 },
  { name: 'Chicago', emoji: '🌆', level: 3 },
  { name: 'Boston', emoji: '🦞', level: 3 },
  { name: 'Miami', emoji: '🏖️', level: 3 },
  { name: 'Austin', emoji: '🎸', level: 3 },
  { name: 'Toronto', emoji: '🍁', level: 3 },
  { name: 'Vancouver', emoji: '🏔️', level: 3 },
  { name: 'Mexico City', emoji: '🌮', level: 3, aliases: ['cdmx'] },
  { name: 'Sydney', emoji: '🦘', level: 3 },
  { name: 'Melbourne', emoji: '☕', level: 3 },
  { name: 'Auckland', emoji: '🥝', level: 3 },
  { name: 'Cape Town', emoji: '⛰️', level: 3 },
  { name: 'Nairobi', emoji: '🦒', level: 3 },
  { name: 'Mauritius', emoji: '🏝️', level: 1 },
  { name: 'Seychelles', emoji: '🏝️', level: 1 },
  { name: 'USA', emoji: '🇺🇸', level: 1, aliases: ['united states', 'usa trip'] },
  { name: 'Canada', emoji: '🍁', level: 1 },
  { name: 'Australia', emoji: '🦘', level: 1 },
  { name: 'New Zealand', emoji: '🥝', level: 1 },
];
